- name: Copy Backup Script to Backup Server
  template:
    src: backup_template.j2
    dest: /cb-data/{{ cluster_name }}.sh
    owner: root
    group: root
    mode: '0777'
- name: Add new Crontab Job for Periodic Backup"
  cron:
    name: "Add Backup job for the Cluste {{ cluster_name }}"
    minute: "{{ period }}"
    job: "{{ mountpoint }}/{{ cluster_name }}.sh"